check:
    global:
        statements: 0
        lines: 0
        branches: 0
        functions: 0
reporting:
    watermarks:
        statements: [80, 100]
        lines: [80, 100]
        functions: [80, 100]
        branches: [80, 100]